[package]
name = "http-capture"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.4"
crossterm = "0.27.0"
etherparse = "0.14.3"
httparse = "1.8.0"
pcap = "2.0.0"
ratatui = "0.26.2"
