FROM --platform=linux/amd64 centos:7

RUN yum -y update && \
    yum -y install \
       ca-certificates \
       curl \
       gcc \
       glibc-devel

COPY certs/* /etc/pki/ca-trust/source/anchors/
RUN update-ca-trust extract

RUN yum -y install libpcap-devel

RUN mkdir /rust
WORKDIR /rust

RUN sh -c "curl https://sh.rustup.rs -sSf | sh -s -- -y"
